[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first | replace(from="Added", to="âœ¨ Added") | replace(from="Fixed", to="ğŸ› Fixed") | replace(from="Documentation", to="ğŸ“š Documentation") | replace(from="Performance", to="âš¡ Performance") | replace(from="Refactored", to="ğŸ”„ Refactored") | replace(from="Styling", to="ğŸ’… Styling") | replace(from="Testing", to="ğŸ§ª Testing") | replace(from="Miscellaneous Tasks", to="ğŸ”§ Miscellaneous Tasks") | replace(from="Dependencies", to="ğŸ“¦ Dependencies") }}
{% for commit in commits %}
- {% if commit.scope %}**{{commit.scope}}**: {% endif %}{{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}

{% if contributors %}
## Contributors
{% for contributor in contributors %}
- [@{{ contributor.username }}]({{ self::remote_url() }}/commits?author={{ contributor.username }})
{% endfor %}
{% endif %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Added"},
  { message = "^fix", group = "Fixed"},
  { message = "^doc", group = "Documentation"},
  { message = "^perf", group = "Performance"},
  { message = "^refactor", group = "Refactored"},
  { message = "^style", group = "Styling"},
  { message = "^test", group = "Testing"},
  { message = "^chore\\(release\\): prepare for", skip = true},
  { message = "^chore", group = "Miscellaneous Tasks"},
  { message = "^build", group = "Dependencies"},
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

[remote.github]
token = "${{ secrets.GITHUB_TOKEN }}"